functionsDirectory = "/Users/avi/Library/CloudStorage/Dropbox/claude/symptom-tracker/netlify/functions"
functionsDirectoryOrigin = "config"
plugins = []
headers = []
redirects = []

[build]
publish = "/Users/avi/Library/CloudStorage/Dropbox/claude/symptom-tracker/dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"
functions = "/Users/avi/Library/CloudStorage/Dropbox/claude/symptom-tracker/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"